//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyBank.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccNumb {
            get {
                return ResourceManager.GetString("AccNumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number required.
        /// </summary>
        public static string AccountNumberRequired {
            get {
                return ResourceManager.GetString("AccountNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts are absent.
        /// </summary>
        public static string AccountsAreAbsent {
            get {
                return ResourceManager.GetString("AccountsAreAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account status required.
        /// </summary>
        public static string AccountStatusRequired {
            get {
                return ResourceManager.GetString("AccountStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AccountsTitle {
            get {
                return ResourceManager.GetString("AccountsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type required.
        /// </summary>
        public static string AccountTypeRequired {
            get {
                return ResourceManager.GetString("AccountTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new account.
        /// </summary>
        public static string AddAccount {
            get {
                return ResourceManager.GetString("AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add bank product.
        /// </summary>
        public static string AddBankProduct {
            get {
                return ResourceManager.GetString("AddBankProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new client.
        /// </summary>
        public static string AddClient {
            get {
                return ResourceManager.GetString("AddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add currency.
        /// </summary>
        public static string AddCurrency {
            get {
                return ResourceManager.GetString("AddCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add money.
        /// </summary>
        public static string AddMoney {
            get {
                return ResourceManager.GetString("AddMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add photo.
        /// </summary>
        public static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you&apos;ve entered correct information and try again!.
        /// </summary>
        public static string AdviceMessageInClientListSearch {
            get {
                return ResourceManager.GetString("AdviceMessageInClientListSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow web-accees.
        /// </summary>
        public static string AllowWebAccees {
            get {
                return ResourceManager.GetString("AllowWebAccees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount required.
        /// </summary>
        public static string AmountRequired {
            get {
                return ResourceManager.GetString("AmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to add money?.
        /// </summary>
        public static string AskToAddMoney {
            get {
                return ResourceManager.GetString("AskToAddMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string AskToDeleteCurrency {
            get {
                return ResourceManager.GetString("AskToDeleteCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available amount.
        /// </summary>
        public static string AvailableAmount {
            get {
                return ResourceManager.GetString("AvailableAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to profile.
        /// </summary>
        public static string BackToProfile {
            get {
                return ResourceManager.GetString("BackToProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank accounts.
        /// </summary>
        public static string BankAccounts {
            get {
                return ResourceManager.GetString("BankAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank accounts balance.
        /// </summary>
        public static string BankAccountsBalance {
            get {
                return ResourceManager.GetString("BankAccountsBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank products.
        /// </summary>
        public static string BankProducts {
            get {
                return ResourceManager.GetString("BankProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PId number required.
        /// </summary>
        public static string BirthDateRequired {
            get {
                return ResourceManager.GetString("BirthDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter number of months to calculate interests..
        /// </summary>
        public static string CalculateMessage {
            get {
                return ResourceManager.GetString("CalculateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client required.
        /// </summary>
        public static string ClientIdRequired {
            get {
                return ResourceManager.GetString("ClientIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter surname or identification number.
        /// </summary>
        public static string ClientListSearchTypeRequirement {
            get {
                return ResourceManager.GetString("ClientListSearchTypeRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client not found.
        /// </summary>
        public static string ClientNotFound {
            get {
                return ResourceManager.GetString("ClientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients list.
        /// </summary>
        public static string ClientsList {
            get {
                return ResourceManager.GetString("ClientsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client list.
        /// </summary>
        public static string ClientsListTitle {
            get {
                return ResourceManager.GetString("ClientsListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients passport.
        /// </summary>
        public static string ClientsPassport {
            get {
                return ResourceManager.GetString("ClientsPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients photo.
        /// </summary>
        public static string ClientsPhotoTitle {
            get {
                return ResourceManager.GetString("ClientsPhotoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients profile.
        /// </summary>
        public static string ClientsProfile {
            get {
                return ResourceManager.GetString("ClientsProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients profile.
        /// </summary>
        public static string ClientsProfileTitle {
            get {
                return ResourceManager.GetString("ClientsProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit name.
        /// </summary>
        public static string CreditName {
            get {
                return ResourceManager.GetString("CreditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency delete.
        /// </summary>
        public static string CurrencyDelete {
            get {
                return ResourceManager.GetString("CurrencyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency required.
        /// </summary>
        public static string CurrencyIdRequired {
            get {
                return ResourceManager.GetString("CurrencyIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies list.
        /// </summary>
        public static string CurrencyList {
            get {
                return ResourceManager.GetString("CurrencyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency name.
        /// </summary>
        public static string CurrencyName {
            get {
                return ResourceManager.GetString("CurrencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency name required.
        /// </summary>
        public static string CurrencyNameRequired {
            get {
                return ResourceManager.GetString("CurrencyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is not Valid.
        /// </summary>
        public static string DateNotValid {
            get {
                return ResourceManager.GetString("DateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must have a formal like (0.00 or 0.0 or 0).
        /// </summary>
        public static string DecimalFormat {
            get {
                return ResourceManager.GetString("DecimalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit name.
        /// </summary>
        public static string DepositName {
            get {
                return ResourceManager.GetString("DepositName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposits.
        /// </summary>
        public static string Deposits {
            get {
                return ResourceManager.GetString("Deposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe the problem.
        /// </summary>
        public static string DescribeTheProblem {
            get {
                return ResourceManager.GetString("DescribeTheProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early termination.
        /// </summary>
        public static string EarlyTermination {
            get {
                return ResourceManager.GetString("EarlyTermination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early termination.
        /// </summary>
        public static string EarlyTerminationCredit {
            get {
                return ResourceManager.GetString("EarlyTerminationCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit client profile.
        /// </summary>
        public static string EditClient {
            get {
                return ResourceManager.GetString("EditClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit photo.
        /// </summary>
        public static string EditPhoto {
            get {
                return ResourceManager.GetString("EditPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code.
        /// </summary>
        public static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reports.
        /// </summary>
        public static string ErrorReports {
            get {
                return ResourceManager.GetString("ErrorReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Can&apos;t take money from credit account.
        /// </summary>
        public static string ErrorTakeMoneyFromCreditAcc {
            get {
                return ResourceManager.GetString("ErrorTakeMoneyFromCreditAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string ExpDate {
            get {
                return ResourceManager.GetString("ExpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date required.
        /// </summary>
        public static string ExpirationDateRequired {
            get {
                return ResourceManager.GetString("ExpirationDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        public static string FileUpload {
            get {
                return ResourceManager.GetString("FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial reports.
        /// </summary>
        public static string FinancialReports {
            get {
                return ResourceManager.GetString("FinancialReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze.
        /// </summary>
        public static string Freeze {
            get {
                return ResourceManager.GetString("Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are signed in as.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest rate.
        /// </summary>
        public static string InterestRate {
            get {
                return ResourceManager.GetString("InterestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is online system user.
        /// </summary>
        public static string IsOnlineUser {
            get {
                return ResourceManager.GetString("IsOnlineUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be 10 characters long.
        /// </summary>
        public static string Len10 {
            get {
                return ResourceManager.GetString("Len10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length must be 8 chars.
        /// </summary>
        public static string Len8 {
            get {
                return ResourceManager.GetString("Len8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in for clients.
        /// </summary>
        public static string LogInForClients {
            get {
                return ResourceManager.GetString("LogInForClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your credentials to enter the system..
        /// </summary>
        public static string LoginHelpMessage {
            get {
                return ResourceManager.GetString("LoginHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogInTitle {
            get {
                return ResourceManager.GetString("LogInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must start with capital letter and have latin characters only.
        /// </summary>
        public static string NameFromCap {
            get {
                return ResourceManager.GetString("NameFromCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must have length from 3 to 20 characters.
        /// </summary>
        public static string NameLen3To20 {
            get {
                return ResourceManager.GetString("NameLen3To20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client has no photo.
        /// </summary>
        public static string NoPhoto {
            get {
                return ResourceManager.GetString("NoPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only digits are allowed.
        /// </summary>
        public static string OnlyDigits {
            get {
                return ResourceManager.GetString("OnlyDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation date.
        /// </summary>
        public static string OperationDate {
            get {
                return ResourceManager.GetString("OperationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation error.
        /// </summary>
        public static string OperationError {
            get {
                return ResourceManager.GetString("OperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact system administrator or operator.
        /// </summary>
        public static string OperationErrorMessage {
            get {
                return ResourceManager.GetString("OperationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators.
        /// </summary>
        public static string Operators {
            get {
                return ResourceManager.GetString("Operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators list.
        /// </summary>
        public static string OperatorsList {
            get {
                return ResourceManager.GetString("OperatorsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport.
        /// </summary>
        public static string Passport {
            get {
                return ResourceManager.GetString("Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay in.
        /// </summary>
        public static string PayIn {
            get {
                return ResourceManager.GetString("PayIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay out.
        /// </summary>
        public static string PayOut {
            get {
                return ResourceManager.GetString("PayOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PId Number.
        /// </summary>
        public static string PIdNum {
            get {
                return ResourceManager.GetString("PIdNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PId number required.
        /// </summary>
        public static string PIdNumberRequired {
            get {
                return ResourceManager.GetString("PIdNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted by.
        /// </summary>
        public static string PostedBy {
            get {
                return ResourceManager.GetString("PostedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted date.
        /// </summary>
        public static string PostedDate {
            get {
                return ResourceManager.GetString("PostedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase rate.
        /// </summary>
        public static string PurchaseRate {
            get {
                return ResourceManager.GetString("PurchaseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient.
        /// </summary>
        public static string Recipient {
            get {
                return ResourceManager.GetString("Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string RegDate {
            get {
                return ResourceManager.GetString("RegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register operator.
        /// </summary>
        public static string RegisterOperator {
            get {
                return ResourceManager.GetString("RegisterOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salling rate.
        /// </summary>
        public static string SallingRate {
            get {
                return ResourceManager.GetString("SallingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        public static string SetToNormal {
            get {
                return ResourceManager.GetString("SetToNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status required.
        /// </summary>
        public static string StatusIdRequired {
            get {
                return ResourceManager.GetString("StatusIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit entry.
        /// </summary>
        public static string SubmitEntry {
            get {
                return ResourceManager.GetString("SubmitEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname required.
        /// </summary>
        public static string SurnameRequired {
            get {
                return ResourceManager.GetString("SurnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname must have length from 3 to 30 characters.
        /// </summary>
        public static string SurnLen3To30 {
            get {
                return ResourceManager.GetString("SurnLen3To30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a picture.
        /// </summary>
        public static string TakeAPicture {
            get {
                return ResourceManager.GetString("TakeAPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total credit amount.
        /// </summary>
        public static string TotalCreditAmount {
            get {
                return ResourceManager.GetString("TotalCreditAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total сredit interests in currency:.
        /// </summary>
        public static string TotalCreditInterests {
            get {
                return ResourceManager.GetString("TotalCreditInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total deposited amount.
        /// </summary>
        public static string TotalDepositedAmount {
            get {
                return ResourceManager.GetString("TotalDepositedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total deposits interests.
        /// </summary>
        public static string TotalDepositInterests {
            get {
                return ResourceManager.GetString("TotalDepositInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Can&apos;t transfer money from credit account.
        /// </summary>
        public static string TransferErrorFromCreditAcc {
            get {
                return ResourceManager.GetString("TransferErrorFromCreditAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer funds.
        /// </summary>
        public static string TransferFunds {
            get {
                return ResourceManager.GetString("TransferFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer money.
        /// </summary>
        public static string TransMoney {
            get {
                return ResourceManager.GetString("TransMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type required.
        /// </summary>
        public static string TypeIdRequired {
            get {
                return ResourceManager.GetString("TypeIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the symbols.
        /// </summary>
        public static string TypeTheSymbols {
            get {
                return ResourceManager.GetString("TypeTheSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the text.
        /// </summary>
        public static string TypeTheText {
            get {
                return ResourceManager.GetString("TypeTheText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload client photo.
        /// </summary>
        public static string UploadClientPhotoTitle {
            get {
                return ResourceManager.GetString("UploadClientPhotoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload image.
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload passport scan.
        /// </summary>
        public static string UploadPassportScan {
            get {
                return ResourceManager.GetString("UploadPassportScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Easy Bank!.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widthdraw money.
        /// </summary>
        public static string WidthdrawMoney {
            get {
                return ResourceManager.GetString("WidthdrawMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw funds.
        /// </summary>
        public static string WithdrawFunds {
            get {
                return ResourceManager.GetString("WithdrawFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong capcha input.
        /// </summary>
        public static string WrongCapchaInput {
            get {
                return ResourceManager.GetString("WrongCapchaInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong input type. Image is expected..
        /// </summary>
        public static string WrongFileChoose {
            get {
                return ResourceManager.GetString("WrongFileChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only for admins and operators.
        /// </summary>
        public static string WrongLogInForAdminAndOperPage {
            get {
                return ResourceManager.GetString("WrongLogInForAdminAndOperPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only for clients.
        /// </summary>
        public static string WrongLogInForClientPage {
            get {
                return ResourceManager.GetString("WrongLogInForClientPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re logged in as.
        /// </summary>
        public static string YouAreLoggedInAs {
            get {
                return ResourceManager.GetString("YouAreLoggedInAs", resourceCulture);
            }
        }
    }
}
